//===================================================//
//                                                   //
//              ~ Acora IRC Services ~               //
//                                                   //
//       Acora (C) 2011 Acora Development Team       //
// Please see the file CREDITS for more information. //
//                                                   //
//   This program is free but copyrighted software   //
//      Please see the file COPYING for details.     //
//                                                   //
// This file is autogenerated by configure and will  //
//      be replaced next time configure is ruN.      //
//                                                   //
//===================================================//

#ifndef CONFIG_H
#define CONFIG_H

namespace config
{
	// acora version
	const char VERSION[] = "0.1-git";

	// acora root directory
	const char ROOTDIR[] = "/home/ricki/nevitus/";

	// directory where socketengines are installed
	const char SOCKDIR[] = "/home/ricki/nevitus/bin/socketengines/";
	// directory where ircdprotocols are installed
	const char IRCDDIR[] = "/home/ricki/nevitus/bin/ircdprotocols/";
	// directory where diskmanagers are installed
	const char DISKDIR[] = "/home/ricki/nevitus/bin/diskmanagers/";
	// directory where modules are installed
	const char MODDIR[] = "/home/ricki/nevitus/bin/modules/";

	// config file directory
	const char CONFDIR[] = "/home/ricki/nevitus/data/conf/";
} // namespace config

#endif // CONFIG_H
